//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChromeMultipleLogins {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class application : global::System.Configuration.ApplicationSettingsBase {
        
        private static application defaultInstance = ((application)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new application())));
        
        public static application Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string urlhistory {
            get {
                return ((string)(this["urlhistory"]));
            }
            set {
                this["urlhistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection usernames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["usernames"]));
            }
            set {
                this["usernames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int rowcount {
            get {
                    return ((int)(this["rowcount"]));
            }
            set {
                this["rowcount"] = value;
            }
        }
    }
}